---
# tasks file for jpnewman.apache
- name: Install apache
  apt: name={{ item }} state=present update_cache=yes cache_valid_time={{ apt_cache_valid_time }}
  with_items:
    - apache2
    - apache2-utils

- name: Enable modules
  file:
    src: "{{ apache_path }}/mods-available/{{ item }}"
    dest: "{{ apache_path }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Create directory to store ssl crt
  tags: ["ssl"]
  file: path={{ ssl_cert_directory }} state=directory

- name: Copy SSL cert
  tags: ["ssl"]
  copy: src={{ ssl_cert_local_directory }}/{{ ssl_cert }} dest={{ ssl_cert_directory }}
  notify: restart apache

- name: Copy SSL key
  tags: ["ssl"]
  copy: src={{ ssl_cert_local_directory }}/{{ ssl_key }} dest={{ ssl_cert_directory }}
  notify: restart apache

- name: Create apache log directory
  file:
    path: "{{ apache_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Update vhost
  template:
    src: vhost.conf.j2
    dest: "{{ apache_path }}/sites-available/{{ apache_vhosts_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Enabled vhost
  file:
    src: "{{ apache_path }}/sites-available/{{ apache_vhosts_file }}"
    dest: "{{ apache_path }}/sites-enabled/{{ apache_vhosts_file }}"
    state: link
  notify: restart apache

- name: Removing default vhost
  file:
    path: "{{ apache_path }}/sites-enabled/{{ apache_default_vhost_file }}"
    state: absent
  notify: restart apache
  when: apache_default_delete_vhost
